# Secret of NumPy
There are not 10 Python integers under the covers

In [2]:
import numpy as np
digits = np.array(range(10))
digits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
slow_digits = list(range(10))
slow_digits

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
digits.dtype

dtype('int64')

In [5]:
# Operations
digits.shape

(10,)

In [6]:
digits + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
digits

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
digits + digits

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.sin(digits)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [10]:
# Creation
np.arange(3)

array([0, 1, 2])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [14]:
np.eye?

Signature:
np.eye(
    N,
    M=None,
    k=0,
    dtype=<class 'float'>,
    order='C',
    *,
    device=None,
    like=None,
)
Docstring:
Return a 2-D array with ones on the diagonal and zeros elsewhere.

Parameters
----------
N : int
  Number of rows in the output.
M : int, optional
  Number of columns in the output. If None, defaults to `N`.
k : int, optional
  Index of the diagonal: 0 (the default) refers to the main diagonal,
  a positive value refers to an upper diagonal, and a negative value
  to a lower diagonal.
dtype : data-type, optional
  Data-type of the returned array.
order : {'C', 'F'}, optional
    Whether the output should be stored in row-major (C-style) or
    column-major (Fortran-style) order in memory.
device : str, optional
    The device on which to place the created array. Default: None.
    For Array-API interoperability only, so must be ``"cpu"`` if passed.

    .. versionadded:: 2.0.0
like : array_like, optional
        Reference object to allow the creat

In [15]:
np.diag(range(3))

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [16]:
np.linspace(0, 10, num=12)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])

In [17]:
# Random Creation
np.random.random(3) # between [0,1)

array([0.35531042, 0.51789365, 0.71441021])

In [18]:
rng = np.random.default_rng()
rng.integers(low=11, high=15, size=5) # 5 between [11,15)

array([12, 11, 14, 13, 14])

In [19]:
np.random.bytes(5) # 5 bytes

b'\xfa\xe8\x13L9'

In [20]:
np.random.randn(3) #normal distribution

array([ 0.0739187 , -1.71559979,  0.19589779])

# More Numpy

In [21]:
# Array features
dir(digits)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [22]:
len(dir(digits))

166

In [23]:
digits.mean()

np.float64(4.5)

In [24]:
# Numpy Features
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmin',
 'argpartition',
 'argsort',
 'argwhere',
 'around',
 'array',
 'arr

In [25]:
len(dir(np))

532

In [26]:
np.log(digits)

C:\Users\572856\AppData\Local\Temp\ipykernel_25244\3230101025.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(digits)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [27]:
np.log(digits+1)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

# NumPy Dimensions

In [28]:
nums = np.arange(100).reshape(20, 5)
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [29]:
nums.transpose()

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75,
        80, 85, 90, 95],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76,
        81, 86, 91, 96],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77,
        82, 87, 92, 97],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58, 63, 68, 73, 78,
        83, 88, 93, 98],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79,
        84, 89, 94, 99]])

In [30]:
# Axis - two dimensional
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [31]:
nums.mean()

np.float64(49.5)

In [32]:
nums.mean(axis=0)

array([47.5, 48.5, 49.5, 50.5, 51.5])

In [33]:
nums.mean(axis=1, keepdims=True)

array([[ 2.],
       [ 7.],
       [12.],
       [17.],
       [22.],
       [27.],
       [32.],
       [37.],
       [42.],
       [47.],
       [52.],
       [57.],
       [62.],
       [67.],
       [72.],
       [77.],
       [82.],
       [87.],
       [92.],
       [97.]])

In [35]:
# three dimensional
b = np.arange(70).reshape(7, 5, 2)
b

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69]]])

In [36]:
b.mean(axis=0, keepdims=True)

array([[[30., 31.],
        [32., 33.],
        [34., 35.],
        [36., 37.],
        [38., 39.]]])

In [37]:
b.mean(axis=1, keepdims=True)

array([[[ 4.,  5.]],

       [[14., 15.]],

       [[24., 25.]],

       [[34., 35.]],

       [[44., 45.]],

       [[54., 55.]],

       [[64., 65.]]])

In [38]:
b.mean(axis=2, keepdims=True)

array([[[ 0.5],
        [ 2.5],
        [ 4.5],
        [ 6.5],
        [ 8.5]],

       [[10.5],
        [12.5],
        [14.5],
        [16.5],
        [18.5]],

       [[20.5],
        [22.5],
        [24.5],
        [26.5],
        [28.5]],

       [[30.5],
        [32.5],
        [34.5],
        [36.5],
        [38.5]],

       [[40.5],
        [42.5],
        [44.5],
        [46.5],
        [48.5]],

       [[50.5],
        [52.5],
        [54.5],
        [56.5],
        [58.5]],

       [[60.5],
        [62.5],
        [64.5],
        [66.5],
        [68.5]]])

In [39]:
# NumPy Indexing & Slicing
# Similar to python, but not limited to one dimension
nums

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [40]:
# row 0 only
nums[0]

array([0, 1, 2, 3, 4])

In [41]:
# rows 0, 5, 10
nums[[0, 5, 10]]

array([[ 0,  1,  2,  3,  4],
       [25, 26, 27, 28, 29],
       [50, 51, 52, 53, 54]])

In [42]:
# can slice along multiple dimensions:
nums[0:10] # first 10 rows

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [44]:
# all rows, 3 columns
nums[:, 0:3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17],
       [20, 21, 22],
       [25, 26, 27],
       [30, 31, 32],
       [35, 36, 37],
       [40, 41, 42],
       [45, 46, 47],
       [50, 51, 52],
       [55, 56, 57],
       [60, 61, 62],
       [65, 66, 67],
       [70, 71, 72],
       [75, 76, 77],
       [80, 81, 82],
       [85, 86, 87],
       [90, 91, 92],
       [95, 96, 97]])